---
- name: Configurar
  hosts: db01

  user: vagrant
  become: yes
  vars:
  - dbname: "db01"
  - dbusername: "root"
  - dbuspassword: "dqm50vnc"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql