Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "docker"
  config.vm.network "private_network", ip: "192.168.0.5"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
  config.vm.provision "shell", path: "provision.sh"
end